name: TorchDA
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - jupyter
  - matplotlib
  - pytest
  - scikit-image
  - pip:
    - -r requirements.txt
    - -e .