name: pytest-conda

# Only run this when the branch changes
on: [push, workflow_dispatch]

jobs:
  create-env:
    name: conda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - uses: actions/checkout@v3
        
      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: defaults, conda-forge, pytorch, nvidia
          auto-activate-base: false
          activate-environment: ci
          environment-file: environment.yml

      - name: Test with pytest
        run: |
          pytest -p no:warnings tests/
